# Generated by Django 4.1.2 on 2022-10-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.TextField(),
        ),
    ]
